### ISSUE TITLE
支持上传前回调吗？

### ISSUE THREAD

**Issue by hasbug** [overtrue/vue-avatar-cropper#1]
很高兴能找到你这个插件。
我的需求需要在选完图片后进行一些异步操作再附带一些数据上传图片，当前插件能够做到吗？ 谢谢。急用。期望指导！

**Comment by overtrue** [comment]
@hasbug 我来加事件

**Comment by overtrue** [comment]
不过你可以自己用 `upload-handler` 这个来自定义上传逻辑，这样也许逻辑不会太分散一些。

**Comment by passioncsu** [comment]
redeme 里面的 handleUploading(form. xhr) 是逗号,写错了吧
