### ISSUE TITLE
Example of how to use with Vuex

### ISSUE THREAD

**Issue by scp-nm** [overtrue/vue-avatar-cropper#10]
Hi there,

Thanks for putting together this component - looks like it will be very useful.

Would you be able to put together an example of how this component could be used with Vuex (i.e. upload to a Vuex action)?

Many thanks,

Neil

**Comment by overtrue** [comment]
You can set `upload-handler` to you Vuex action or create a method to dispatch Vuex action.

**Comment by overtrue** [comment]
@scp-nm I made a online demo: [![Edit vue-avatar-cropper-demo](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/9lo653jpz4)

**Comment by Guolefeng** [comment]
![un](https://user-images.githubusercontent.com/20988243/42443522-5088ff50-83a0-11e8-9e06-66c96cb52d98.png)
