### ISSUE TITLE
I would like to upload the image in following format how can i get the cropped formdata?

### ISSUE THREAD

**Issue by JISSJOHNSON** [overtrue/vue-avatar-cropper#129]
I would like to upload the image in following format how can i get the cropped formdata?

    cropperHandler(cropper) {
       console.log(cropper.getCroppedCanvas().toDataURL(this.cropperOutputMime));
      uploaddata = formdata.append('photo',cropper)
      axios({
        method: "POST",
        url: "http://localhost:5000/photo/",
        headers: {
          to: "token"
        },
        data: uploaddata
      });
    },

_Originally posted by @JISSJOHNSON in https://github.com/overtrue/vue-avatar-cropper/issues/23#issuecomment-554237778_

**Comment by JISSJOHNSON** [comment]
cropperHandler(cropper) {
      var imgdat = cropper.getCroppedCanvas().toDataURL(this.cropperOutputMime);
      var file = this.dataURLtoFile(imgdat, "test.png");
      let formData = new FormData();
      formData.append("photo", file);
      axios({
        method: "POST",
        url: "/product/testupload/",
        headers: {
          "Content-Type": "multipart/form-data",
          to: "token"
        },
        data: formData
      });
    },

    dataURLtoFile(dataurl, filename) {
      var arr = dataurl.split(","),
        mime = arr[0].match(/:(.*?);/)[1],
        bstr = atob(arr[1]),
        n = bstr.length,
        u8arr = new Uint8Array(n);

      while (n--) {
        u8arr[n] = bstr.charCodeAt(n);
      }

      return new File([u8arr], filename, { type: mime });
    },
thanks to the thread [https://stackoverflow.com/questions/35940290/how-to-convert-base64-string-to-javascript-file-object-like-as-from-file-input-f/38935990#38935990]

**Comment by JISSJOHNSON** [comment]
how can i get the original file name via for above mentioned instance?

**Comment by waLplanet** [comment]
to do so you should listen to changes in the comp:
      @changed="cropperAvatarChanged"

and in the method you receive the file, so you can display the filename:
  cropperAvatarChanged(file, reader) {
      console.log(file.name);
}

**Comment by waLplanet** [comment]
> how can i get the original file name via above mentioned instance?

to do so you should listen to changes in the comp:
@Changed="cropperAvatarChanged"

and in the method you receive the file, so you can display the filename:
cropperAvatarChanged(file, reader) {
console.log(file.name);
}

**Comment by JISSJOHNSON** [comment]
Thanks

**Comment by waLplanet** [comment]
> Thanks

ok, now yo can close the issue
