### ISSUE TITLE
Window not defined on refresh page

### ISSUE THREAD

**Issue by raloeasy** [overtrue/vue-avatar-cropper#130]
Hi, i use this component in a page. When i refresh the page from browser the page does not work and show me Window not defined error in Vue-avatar-cropper component. I already tried to put the component is `<client-only>` tag but there is the same error. 
How i can to solve this?
Thanks

**Comment by Fmoralesotero** [comment]
Try importing like this:
 components: { 
    'avatar-cropper': () => import('vue-avatar-cropper')
  }

**Comment by raloeasy** [comment]
It works but i found this error on console : 
`vendors.app.js:28491 error [Vue warn]: Failed to resolve async component: () => Promise.resolve(/*! import() */).then(__webpack_require__.t.bind(null, /*! vue-avatar-cropper */ "vue-avatar-cropper", 7))
Reason: ReferenceError: window is not defined `
Thanks for now

**Comment by overtrue** [comment]
@raloeasy SSR ？

**Comment by DavidEbrahimi** [comment]
i have this error too.when i refresh the page this error shows

**Comment by mkalayci35** [comment]
+1 SSR problem
