### ISSUE TITLE
上传gif图片，为什么变成image/png类型了

### ISSUE THREAD

**Issue by Alvazz** [overtrue/vue-avatar-cropper#146]
<avatar-cropper
@uploading="handleUploading"
@uploaded="handleUploaded"
@completed="handleCompleted"
@error="handlerError"
trigger="#pick-avatar"
upload-url="https://test.abc.com/logoupload"
:output-mime="outmime"
:output-options="size"
:cropper-options="coption"
:upload-headers="{'X-CSRF-Token': csrf}"
>

this.outmime = 'image/gif'

**Comment by ferretwithaberet** [comment]
Cropper.js, which is a dependency of this project, does not support cropping gifs by default. There is [cropperjs-gif](https://github.com/wmlgl/cropperjs-gif) though. Best case scenario, we will not package `cropper.js` with `vue-avatar-cropper`(I do not know why `cropper.js` is injected in the production code of `vue-avatar-cropper`, in my opinion it should be a dependency in the `package.json`) and instead, when you use the `vue-avatar-cropper` component, you will pass the instance of `cropper.js` as a prop, then the component will use the passed instance to crop images. This way the user will not have both `cropper.js` packages installed when he only really needs one.

**Comment by ferretwithaberet** [comment]
I might add an optional dependency on `cropperjs-gif` for GIF support.
