### ISSUE TITLE
What should we put as the upload-url? 

### ISSUE THREAD

**Issue by Jeffreymurray95** [overtrue/vue-avatar-cropper#189]
New to VUE.js I keep getting a 404 URL not defined error for the upload-url property. What should we put here. Just confused because the demo says "Oops! Something went wrong" and the picture doesn't update. 
Thanks, It looks like a very useful component! just trying to figure out how to use it!

**Comment by overtrue** [comment]
You must use a valid server URL to upload the avatar image. The demo server URL was broken. I will fix that.

**Comment by Jeffreymurray95** [comment]
Got it thank you! So would this work with Firestore?
