### ISSUE TITLE
第一次使用有点不会 纠结了好久，希望超哥 帮帮忙

### ISSUE THREAD

**Issue by Aliceco** [overtrue/vue-avatar-cropper#2]
upload-url="/files/upload/" 写的是保存图片的路径还是接口 我写了 全部都是 404 有点小萌新
updateUserAvatar 这个写在 methods 属性里可以吗？ 我连第一关都没有过~~~

POST http://localhost:3000/files/upload/ 404 (Not Found)  我也试着换过路径都是 404 
(anonymous) @ index.js?96fe:1
VM19050:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.a.onreadystatechange (index.js?96fe:1)

**Comment by Aliceco** [comment]
解决了但是，为啥返回数据如下：:
error:0
name:"blob"
size:70686
tmp_name:"D:\xampp\tmp\php2B81.tmp"
type:"image/png"
这样的数据 tmp_name是路径？tmp不是 临时文件嘛这么使用

**Comment by overtrue** [comment]
1. 这个不限制你返回啥，它只是将文件上传到你指定的 URL
2. 上传完的事情是你自己处理的，`updateUserAvatar` 是你自己指定的方法名，你服务器端的返回值将会直接调用这个方法，你自己拿来怎么处理是你自己决定的，已经与这个组件没有关系了，它做的工作就是：选择图片 -> 裁剪 -> 将裁剪结果上传到你指定的地址，结束， 没有其它逻辑了。

**Comment by Aliceco** [comment]
好的

**Comment by Aliceco** [comment]
超哥能不能有个例子
