### ISSUE TITLE
How to validate other fields before submit

### ISSUE THREAD

**Issue by daniiprado** [overtrue/vue-avatar-cropper#20]
How can I prevent submit if additional fields are empty? Thank you
![captura de pantalla 2018-05-16 a la s 12 30 01 p m](https://user-images.githubusercontent.com/12104660/40133284-e824135c-5904-11e8-8d7b-656287e58388.png)

**Comment by overtrue** [comment]
@daniiprado 
```
 methods: {
    onSubmit() {
        //...
        if (this.name.length < 5) {
             return false;
        }
    }
}
```
