### ISSUE TITLE
The size of the image file gets bigger.

### ISSUE THREAD

**Issue by himeyon** [overtrue/vue-avatar-cropper#216]
If you select a jpeg file and upload it without clipping, the file size will be larger.
With the image file you used, it's about 5 times larger!

The image was taken with an iphone XS Max and is not a special image.

[Image before upload.](https://www.dropbox.com/s/rhtfvbnt3yjgsae/before.jpg?dl=0)
About 2MB

[Image after upload](https://www.dropbox.com/s/ovu77e067rq5ayr/after.png?dl=0)
About 10MB

**Comment by himeyon** [comment]
Issue as a reference.
https://github.com/fengyuanchen/cropper/issues/542

https://github.com/overtrue/vue-avatar-cropper/blob/b6daa41b66747091e08f96a89b13af6de8559a8f/src/AvatarCropper.vue#L194
For example, in the case of jpegs, the file size was not increased when 'image/jpeg' was specified.

**Comment by himeyon** [comment]
@overtrue 
It's closed as it resolved itself.
Thank you.

**Comment by overtrue** [comment]
@himeyon You are welcome!
