### ISSUE TITLE
custom upload handler

### ISSUE THREAD

**Issue by waLplanet** [overtrue/vue-avatar-cropper#23]
I would like to use my own method to upload the cropped image by axios instead of uploading it from the component itself, since in some cases I will want a patch and not a post, and other parameters of the call. is this possible? I can not do it

thanks in advance, I really like this component

**Comment by waLplanet** [comment]
solved! was easy:

\<avatar-cropper
            :upload-handler="**cropperHandler**"
            trigger="#cropper-trigger"
            :output-mime="cropperOutputMime"
            :output-quality="0.8"
            :output-options="cropperOutputOptions"
            :labels="cropperLabels"
            :cropper-options="cropperOptions"
            />

and in my methods:

**cropperHandler** (cropper) {
      console.log(cropper.getCroppedCanvas().toDataURL(this.cropperOutputMime))
    }

**Comment by overtrue** [comment]
👍

**Comment by ilanbenyos** [comment]
greate componet- simple and easy to use.

just to add that in that case you'll have to leave the 'upload-url' empty.

**Comment by JISSJOHNSON** [comment]
I would like to upload the image in following format how can i get the cropped formdata?

    cropperHandler(cropper) {
       console.log(cropper.getCroppedCanvas().toDataURL(this.cropperOutputMime));
      uploaddata = formdata.append('photo',cropper)
      axios({
        method: "POST",
        url: "http://localhost:5000/photo/",
        headers: {
          to: "token"
        },
        data: uploaddata
      });
    },

**Comment by waLplanet** [comment]
hi Jiss, the img generated is a base64 string, so in the cropperHandler method you should send it throught data, I mean this way:

data: cropper.getCroppedCanvas().toDataURL(this.cropperOutputMime)

if you want to upload a file, you should convert the base64 to a file first.

**Comment by JISSJOHNSON** [comment]
Thanks @waLplanet  it worked
