### ISSUE TITLE
Using with nuxtjs

### ISSUE THREAD

**Issue by scasic** [overtrue/vue-avatar-cropper#25]
Trying to use vue-avatar-cropper in nuxtjs project. After including it as local or global component nuxt returns an error: 
![image](https://user-images.githubusercontent.com/11944311/44572730-70d47800-a78d-11e8-8aeb-71e525aaaac0.png)

Please advise how cropper can be correctly attached?

**Comment by overtrue** [comment]
https://github.com/nuxt/nuxt.js/issues?utf8=%E2%9C%93&q=self+is+not+defined
