### ISSUE TITLE
Not working when `vue-avatar-cropper` is inside of a modal.

### ISSUE THREAD

**Issue by tborges** [overtrue/vue-avatar-cropper#253]
Thanks for this great plugin!

I've been working on this issue for a couple of hrs now. When I add `vue-avatar-cropper` inside of a modal, it doesn't work properly. It works fine without a modal. Click on the modal **"Launch demo modal"** button, then try to add/load a foto. There are no console errors nothing.

**I was able to duplicate the issue below.**
https://codesandbox.io/s/gracious-snow-qnce4

Thank you

**Comment by overtrue** [comment]
[![Edit clever-rgb-6kuyz](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/clever-rgb-6kuyz?fontsize=14&hidenavigation=1&theme=dark)
