### ISSUE TITLE
does it has english language?

### ISSUE THREAD

**Issue by naveen84123** [overtrue/vue-avatar-cropper#3]

**Comment by overtrue** [comment]
button labels?

**Comment by overtrue** [comment]
Hi, @naveen84123 plz update to v0.0.14 and using props `labels` to setting button label:

```html
<avatar-cropper
    trigger="#set-avatar"
    upload-url="/files/upload"
    :uploaded="updateUserAvatar"
    :labels="{submit: 'OK', cancel: 'Cancel'}"
></avatar-cropper>
```

**Comment by juicycool92** [comment]
> Hi, @naveen84123 plz update to v0.0.14 and using props `labels` to setting button label:
> 
> ```
> <avatar-cropper
>     trigger="#set-avatar"
>     upload-url="/files/upload"
>     :uploaded="updateUserAvatar"
>     :labels="{submit: 'OK', cancel: 'Cancel'}"
> ></avatar-cropper>
> ```

it will be nice if you post this guide on readme too :>
it's real easy and simple! i luv it <3

**Comment by juicycool92** [comment]
> > Hi, @naveen84123 plz update to v0.0.14 and using props `labels` to setting button label:
> > ```
> > <avatar-cropper
> >     trigger="#set-avatar"
> >     upload-url="/files/upload"
> >     :uploaded="updateUserAvatar"
> >     :labels="{submit: 'OK', cancel: 'Cancel'}"
> > ></avatar-cropper>
> > ```
> 
> it will be nice if you post this guide on readme too :>
> it's real easy and simple! i luv it <3

oh turn's out, there is posted. my bad :P
