### ISSUE TITLE
微信浏览器兼容问题

### ISSUE THREAD

**Issue by tw815837757** [overtrue/vue-avatar-cropper#32]
在微信浏览器上传图片无响应。其他手机浏览器正常

**Comment by tw815837757** [comment]
选中图片确定后没有任何动作

**Comment by tw815837757** [comment]
1

**Comment by shufangjian** [comment]
@tw815837757 有分析出问题吗

**Comment by tw815837757** [comment]
> @tw815837757 有分析出问题吗

没有,后来自己封装了一个

**Comment by shufangjian** [comment]
> > @tw815837757 有分析出问题吗
> 
> 没有,后来自己封装了一个

微信安卓机 input  accept="image/*" 这样才会触发change事件
