### ISSUE TITLE
No avatar make trigger found

### ISSUE THREAD

**Issue by noelc10** [overtrue/vue-avatar-cropper#33]
Good day,

Everytime I load the component, the "No avatar make trigger found." error triggered from the handlerError method.

`<div v-for="(identity_information, index) in profile.identity_informations" :key="index">
        <img v-if="identity_information.profile_picture" :src="'../../../public/' + identity_information.profile_picture" class="img-circle" width="200" height="200" id="profilePicture">
        <img v-else src="../../../images/profile_picture.png" class="img-circle" width="200" height="200" id="profilePicture">
        <div id="changePic">
          <span><i class="fa fa-camera"></i>Change Picture</span>
        </div>
      </div>
      <avatar-cropper
        @changed="handleChanged"
        @uploading="handleUploading"
        @uploaded="handleUploaded"
        @completed="handleCompleted"
        @error="handlerError"
        upload-url="/api/v1/service-provider/identity-information/saveprofilepicture"
        trigger="#changePic"
        :cropper-options="{
          movable: true,
          zoomable: true
        }"
        :labels="{
          submit: 'Submit',
          cancel: 'Cancel'
        }"
        upload-form-name="file"
        :upload-form-data="{
          'file': file
        }"
        :upload-headers="{
          'Content-Type': 'multipart/form-data',
          'X-Requested-With': 'XMLHttpRequest',
          'Authorization': token
        }"
      />`

`<script>
import axios from 'axios'
import AvatarCropper from 'vue-avatar-cropper'
import { eventHandle } from '../../globalbus'

export default {
  components: {
    AvatarCropper
  },
  data() {
    return {
      user_id: '',
      profile: '',
      file: '',
      token: 'Bearer ' + window.localStorage.getItem('token'),
      button: [
        {
          route_name: 'service-provider.profile',
          title: 'Profile'
    		}
      ],
    	lists: [

    		{
    			route_name: 'service-provider.identity',
          title: 'Identity Information',
          active: false,
          mode : 0
    		},
    		{
        route_name: 'service-provider.medical-education',
          title: 'Medical Education',
          active: false,
          mode : 1
    		},
    		{
        route_name: 'service-provider.saudi',
          title: 'Saudi Commission',
          active: false,
          mode : 1
    		},
    		{
        route_name: 'service-provider.academic',
          title: 'Academic Teaching',
          active: false,
          mode : 1
    		},

    		{
        route_name: 'service-provider.withdraw-methods',
          title: 'Financial & Transactions',
          active: false,
          mode : 1
    		},
    		{
        route_name: 'service-provider.payment-methods',
          title: 'Withdraw Method',
          active: false,
          mode : 1
    		},
    		{
        route_name: 'service-provider.account-settings',
          title: 'Account Settings',
          active: false,
          mode : 1
    		}
    	]
    }
  },

  methods: {
    checkMode(title) {
      this.activate(title)
    },
    getServiceProviderProfile() {
      axios.get('service-provider/profile').then(response => {
        this.user_id = response.data.id;
        this.profile = response.data
      }).catch(error => {
        window.console.log(error.response)
      })
    },
    activate(title) {

      let x = this.lists.length - 1
      while(x >= 0) {
        if (this.lists[x].title == title) {
        this.lists[x].active = true
        } else {
          this.lists[x].active = false
          }
        x -= 1
      }
    },
    saveProfilePicture() {
      let headers =  {
        headers: {
          'Content-Type': 'multipart/form-data',
          'X-Requested-With': 'XMLHttpRequest',
        }
      }

      let formData = new FormData()
      formData.append('file', this.profile)

      axios.post('/service-provider/identity-information/saveprofilepicture', formData, headers).then(response => {
        window.console.log('axios response', response)
        this.getServiceProviderProfile()
      }).catch(error => {
        window.console.log('saveProfilePicture error', error)
      })
    },
    handleChanged(file, reader) {
      window.console.log('file', file)
      window.console.log('reader', reader)
      this.file = file
    },
    handleUploading(form, xhr) {
      window.console.log('uploading...')
      window.console.log('form', form)
      window.console.log('xhr', xhr)
    },
    handleUploaded(response) {
      window.console.log('handleUploaded', response)
      if (response.status == "success") {
        // this.user.avatar = response.url;
        // Maybe you need call vuex action to
        // update user avatar, for example:
        // this.$dispatch('updateUser', {avatar: response.url})
        window.console.log('user avatar updated.')
      }
    },
    handleCompleted(response, form, xhr) {
      window.console.log('handleCompleted', response)
      window.console.log('handleCompleted form', form)
      window.console.log('upload completed.')
    },
    handlerError(message, type, xhr) {
      window.console.log('Oops! Something went wrong...')
      window.console.log('message', message)
      window.console.log('type', type)
      window.console.log('xhr', xhr)
    }
  },
  created() {
    this.getServiceProviderProfile()
  }
}
</script>`

Hope you can respond right now, TIA!

**Comment by overtrue** [comment]
plz make an example here: https://codesandbox.io/

**Comment by noelc10** [comment]
Maybe I can send some screenshots?
I can't really make a sandbox of it since the API URL may having a confidential data.

[component](http://prntscr.com/mb31n7)
[methods](http://prntscr.com/mb32lm)
[error in console](http://prntscr.com/mb32lm)

**Comment by overtrue** [comment]
OK， but show the whole page code please.

**Comment by noelc10** [comment]
https://codesandbox.io/s/6yx26m859r under components/ServiceProvider.vue

**Comment by overtrue** [comment]
@noelc10 You made a mistake: 3 id="handlePic" dom rendered, because you put the trgger button in a for loop.

**Comment by noelc10** [comment]
And where is that exactly? Can you mark it up on the sandbox that I gave you?

**Comment by overtrue** [comment]
just move `<div id="changePic"> <span><i class="fa fa-camera"></i>Change Picture</span> </div>` out of `v-for` div

**Comment by noelc10** [comment]
I see, it's working now, my apologies. I'm just a newbie on Vue.
Glad that you catch that up, sir! Kudos!

**Comment by noelc10** [comment]
One follow up question, why is that when I submit the profile picture, there is no file that catch on the laravel controller?

**Comment by overtrue** [comment]
@noelc10 I am sorry maybe you should refer to my code: https://github.com/overtrue/vue-avatar-cropper/blob/master/src/AvatarCropper.vue#L125-L164

**Comment by noelc10** [comment]
I see, thank you so much sir!

**Comment by noelc10** [comment]
Why is the cropped image are grayscaled when getting the blob?

**Comment by volkangunay** [comment]
Is there any way I can use it inside the for? @overtrue
