### ISSUE TITLE
用cdn引用报错

### ISSUE THREAD

**Issue by gaolin16** [overtrue/vue-avatar-cropper#334]
我想用cdn的方式引用
<script src="/component/node_modules/vue-avatar-cropper/dist/index.js"></script>
但是使用标签时报错：
Unknown custom element: <avatar-cropper> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by overtrue** [comment]
麻烦贴出你的代码

**Comment by gaolin16** [comment]
您好，控件很简洁，特别想用，我们项目是用cdn方式使用vue，element组件就是这么使用的，代码如下：

<div class="text-center">
    <img v-if="userAvatar" :src="userAvatar">
    <button id="pick-avatar">选择一张图片</button>
    <avatar-cropper
      @uploaded="handleUploaded"
      trigger="#pick-avatar"
      upload-url="/files/upload" />
  </div>
</div>
</body>
</html>

<script src="/element/vue.js"></script>
<script src="/element/index.js"></script>
<script src="/component/node_modules/vue-avatar-cropper/dist/index.js"></script>
<script>
  data.userAvatar="";
  methods.handleUploaded=function(resp) {
    this.userAvatar = resp.relative_url;
  }
  const mainVue = new Vue({
    el: '#app',
    data: data,
    methods: methods,
  });
</script>

尝试了多种写法，都没成功，包括使用Vue.use，element组件是可以正常使用的。现在console里报错：Unknown custom element: - did you register the component correctly? For recursive components, make sure to provide the "name" option.

用cdn的方式，使用cropperjs也是可以的，但avatar-cropper不行，麻烦您指点一下，谢谢。

**Comment by gaolin16** [comment]
> 麻烦贴出你的代码

您好，控件很简洁，特别想用，我们项目是用cdn方式使用vue，element组件就是这么使用的，代码如下：
`
<div class="text-center">
    <img v-if="userAvatar" :src="userAvatar">
    <button id="pick-avatar">选择一张图片</button>
    <avatar-cropper
      @uploaded="handleUploaded"
      trigger="#pick-avatar"
      upload-url="/files/upload" />
  </div>
</div>
`
以下是html结束后的引用代码：
`
<script src="/element/vue.js"></script>
<script src="/element/index.js"></script>
<script src="/component/node_modules/vue-avatar-cropper/dist/index.js"></script>
<script>
  data.userAvatar="";
  methods.handleUploaded=function(resp) {
    this.userAvatar = resp.relative_url;
  }
  const mainVue = new Vue({
    el: '#app',
    data: data,
    methods: methods,
  });
</script>
`
尝试了多种写法，都没成功，包括使用Vue.use，element组件是可以正常使用的。现在console里报错：Unknown custom element: - did you register the component correctly? For recursive components, make sure to provide the "name" option.

用cdn的方式，使用cropperjs也是可以的，但avatar-cropper不行，麻烦您指点一下，谢谢。

**Comment by gaolin16** [comment]
您好，Gitthub上代码不换行，我用邮件给您发一下试试。我用element的控件组用这种方式一直没有问题，引用您的控件时报错。


您写的这个控件真的特别简洁，我特别喜欢，我用的是cdn的方式引用vue，代码如下：




<html&gt;
<head&gt;
<script&gt;
var data={};

var methods={};
</head&gt;

<body&gt;
<div id="app"&gt;


<div class="text-center"&gt;
&nbsp; &nbsp; <img v-if="userAvatar" :src="userAvatar"&gt;
&nbsp; &nbsp; <button id="pick-avatar"&gt;选择一张图片</button&gt;
&nbsp; &nbsp; <avatar-cropper
&nbsp; &nbsp; &nbsp; @uploaded="handleUploaded"
&nbsp; &nbsp; &nbsp; trigger="#pick-avatar"
&nbsp; &nbsp; &nbsp; upload-url="/files/upload" /&gt;
</div&gt;



</div&gt;
</body&gt;
</html&gt;


<script src="/element/vue.js"&gt;</script&gt;
<script src="/element/index.js"&gt;</script&gt;
<script src="/component/node_modules/vue-avatar-cropper/dist/index.js"&gt;</script&gt;
<script&gt;
data.userAvatar="";
methods.handleUploaded=function(resp) {         this.userAvatar = resp.relative_url; };


&nbsp; const mainVue = new Vue({
&nbsp; &nbsp; el: '#app',
&nbsp; &nbsp; data: data,
&nbsp; &nbsp; methods: methods,
&nbsp; });
</script&gt;













------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月12日(星期五) 上午10:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [overtrue/vue-avatar-cropper] 用cdn引用报错 (#334)





 
麻烦贴出你的代码

**Comment by overtrue** [comment]
你需要在  new Vue 的时候注册 components 啊
