### ISSUE TITLE
Make cropper options having square

### ISSUE THREAD

**Issue by noelc10** [overtrue/vue-avatar-cropper#34]
Just wondering if there are any possibility to make the cropper circle? Hope you can reply right now.
Thanks in advance.

**Comment by overtrue** [comment]
https://github.com/fengyuanchen/cropperjs

**Comment by overtrue** [comment]
I think it's no need cropper circle, because you can show with`border-radius`.

**Comment by noelc10** [comment]
how can I do that by my component?
When I declare cropper border-radius in my component style, it is not working.
Hope you can reply right now, thanks!
