### ISSUE TITLE
Use same mime output as origin

### ISSUE THREAD

**Issue by lukaszkups** [overtrue/vue-avatar-cropper#35]
Is it possible to don't change mime type in output image, so if I choose PNG image then the output will be PNG, same for JPG etc.?

**Comment by lukaszkups** [comment]
Ok I've managed to make it dynamic so it gets updated on `change` event. 

Found another issue though, when trying to upload SVG image, on Firefox I receive `TypeError: Argument 2 of FormData.append is not an object` - has anyone experienced it? On Chrome it works fine.

**Comment by overtrue** [comment]
@lukaszkups I will fix it as soon as possible.

**Comment by lukaszkups** [comment]
thanks! crossed fingers for quick fix 😁
