### ISSUE TITLE
请问npm上版本更新的问题

### ISSUE THREAD

**Issue by dc3671** [overtrue/vue-avatar-cropper#4]
用yarn安装的，版本是@0.0.14，有一个props在github这里是没有的，事实上也确实不是必须的（如果不用默认handler）而且名字和一个event名字相同，我最后看node_modules里的源码才发现这个问题...

![image](https://user-images.githubusercontent.com/5948851/32086503-51b4d3be-ba9b-11e7-9d22-37ed59728cc6.png)

所以npm上的版本不是自动和这里同步的吗？

**Comment by overtrue** [comment]
更新到 0.0.15 看看

**Comment by dc3671** [comment]
好吧，得手动修改package.json，默认添加的为啥是0.0.14（这个机制我还不是很明白...）

**Comment by overtrue** [comment]
@dc3671 安装的时候会以当时的版本来创建 package.json
