### ISSUE TITLE
A better way to trigger the avatar cropper

### ISSUE THREAD

**Issue by ferretwithaberet** [overtrue/vue-avatar-cropper#436]
At the moment, an `addEventListener` is used to catch the `click` event on the element determined from the `trigger` css selector.

My ideea is to have a boolean prop with v-model and a default value of `false`, which when changed to `true` will trigger the component, when the component closes the boolean will be set back to `false`. This will allow the user of this package to trigger the component in more ways than it is currently available, not only by clicking on an element.

Feel free to propose any other ideas to achieve this result. The whole point of this issue is to brainstorm ways of doing this to achieve the best outcome, I will start working on this feature soon and it might release as v3.0.0.

**Comment by ferretwithaberet** [comment]
@overtrue when you have some time, please test the [improved-trigger](https://github.com/overtrue/vue-avatar-cropper/tree/improved-trigger) branch.

**Comment by overtrue** [comment]
@ferretwithaberet Thanks for your contribution, I've just tested it and I think it's a pretty good solution.
