### ISSUE TITLE
Allow to crop without pick

### ISSUE THREAD

**Issue by ranhsd** [overtrue/vue-avatar-cropper#448]
Hi, love this library. Great job!

I wanted to know if there is a chance to provide the ability to crop image but without pick it ahead.
I mean to allow user to send a already selected image and use this component only to perform the cropping. 

Currently I managed to make it work by using ref and use $ref.cropper.onFileInputChange and there I sent the event of the files but it looks like a workaround and I expect to have the ability to send an already selected photo or even a local one.
![image](https://user-images.githubusercontent.com/3685671/126702924-4a667f11-0052-4730-a621-cfeba1a46a08.png)

I need this feature because in my app I allow users to drag and drop instead of browsing for images and I think that this feature will be amazing.

Thank you!

**Comment by ferretwithaberet** [comment]
Added in Release `3.0.3` in commit ec1dca0d35a694418f23ad56c2c77256621b7941.

When the `trigger` prop changes to `true` and the `file` prop is provided it will use the provided file instead of prompting the user to upload one.
