### ISSUE TITLE
Nuxt upload-handler does not work

### ISSUE THREAD

**Issue by cvalues** [overtrue/vue-avatar-cropper#466]
Hi,

i want to use the avatar cropper in my nuxt project. But to override the upload-handler does not work:
`:upload-handler="cropperHandler"`

```
cropperHandler(cropper) {
 console.log(cropper);
}
```

Also setting custom headers seems not to work?

`:upload-headers="headers"`

Changing the button labels works.

This does not work. Any ideas?

**Comment by ferretwithaberet** [comment]
Check your installed version of `vue-avatar-cropper`. `upload-headers` was replaced by `request-options` in release `4.0.0`.

**Comment by cvalues** [comment]
Hi,
thanks for the quick answer.

Unhandled promise rejection TypeError: Failed to construct 'Request': Request with GET/HEAD method cannot have body.

**Comment by ferretwithaberet** [comment]
> Hi,
> thanks for the quick answer.
> 
> Unhandled promise rejection TypeError: Failed to construct 'Request': Request with GET/HEAD method cannot have body.
> 
> ```
> :request-options="headers"
> 
>     headers: {
>               'X-Requested-With': 'XMLHttpRequest',
>               'X-CSRF-TOKEN': token,
>           },
> ```

Read the updated [README.md](https://github.com/overtrue/vue-avatar-cropper/blob/master/README.md) to know how to use the `request-options` prop. The way you tried above is not how it is meant to be used.

**Comment by cvalues** [comment]
sending the header works now, thanks alot!

last question how to set a custom upload-handler

` :upload-handler="cropperHandler"

      cropperHandler(cropper) {

 
        var imgdat = cropper.getCroppedCanvas().toDataURL(this.cropperOutputMime);
        var file = this.dataURLtoFile(imgdat, "test.png");
        let formData = new FormData();
        formData.append("photo", file);

        axios({
          method: "POST",
          url: "/product/testupload/",
          headers: {
            "Content-Type": "multipart/form-data",
            to: "token"
          },
          data: formData
        });
      },


`

**Comment by ferretwithaberet** [comment]
> sending the header works now, thanks alot!
> 
> last question how to set a custom upload-handler
> ` :upload-handler="cropperHandler"`
> 
> ```
> 
>       cropperHandler(cropper) {
> 
>  
>         var imgdat = cropper.getCroppedCanvas().toDataURL(this.cropperOutputMime);
>         var file = this.dataURLtoFile(imgdat, "test.png");
>         let formData = new FormData();
>         formData.append("photo", file);
> 
>         axios({
>           method: "POST",
>           url: "/product/testupload/",
>           headers: {
>             "Content-Type": "multipart/form-data",
>             to: "token"
>           },
>           data: formData
>         });
>       },
> ```

The way you did it seems to be the right way, can you provide a traceback or something which could help me determine what happened?

**Comment by cvalues** [comment]
what do you mean with traceback? i am using nuxt 2x, vue bootstrap and avatar cropper 4.0.3.

     ```
 <avatar-cropper
                      v-model="trigger"
                      :upload-handler="cropperHandler"
                      :upload-url="uploadUrl"
                      @uploading="handleUploading"
                      @uploaded="handleUploaded"
                      @completed="handleCompleted"
                      @error="handleError"
                  
                    />


```

```
  methods: {
cropperHandler(cropper) {
  console.log(cropper)
}
}
```

the custom function does not dispatch.

**Comment by cvalues** [comment]
okay....i found the problem....:upload-url="uploadUrl"   
it seems that if the url is set the method won't dispatch

**Comment by ferretwithaberet** [comment]
> what do you mean with traceback? i am using nuxt 2x, vue bootstrap and avatar cropper 4.0.3.
> 
> ```
>  ```
> ```
> 
> <avatar-cropper
> v-model="trigger"
> :upload-handler="cropperHandler"
> :upload-url="uploadUrl"
> @uploading="handleUploading"
> @uploaded="handleUploaded"
> @completed="handleCompleted"
> @error="handleError" />
> 
> ```
> 
> ```
> 
> methods: {
> cropperHandler(cropper) {
> console.log(cropper)
> }
> }
> 
> ```
> 
> the custom function does not dispatch. 
> ```

When you get an error in the console, it also has a traceback attached to it. The traceback is the path the code took that caused the error. Open your developer console in your browser and go to the `Console` tab and tell me if you got any errors and which ones.

**Comment by cvalues** [comment]
no erros in the console that was the problem. it was setted the upload url!
