### ISSUE TITLE
How to set max &  min Height & Width: 

### ISSUE THREAD

**Issue by cvalues** [overtrue/vue-avatar-cropper#467]
Hi again,

it seems that the output options are not used

`:output-options="{ width: 100, height: 100, maxWidth: 100, maxHeight: 100  }"`

debug from console , Copper canvasData
```

canvasData:
aspectRatio: 1
height: 300
left: 0
maxHeight: Infinity
maxLeft: 300
maxTop: 300
maxWidth: Infinity
minHeight: 0
minLeft: -300
minTop: -300
minWidth: 0
naturalHeight: 700
naturalWidth: 700
oldLeft: 0
oldTop: 0
top: 0
```

this works.

`cropper.getCroppedCanvas({width: 160, height: 90}).toDataURL(this.cropperOutputMime);`

what goes wrong, thanks for help again!

**Comment by ferretwithaberet** [comment]
`output-options` do not work with `upload-handler`. The user provided `upload-handler` is supposed to do everything that is needed.

[This is the relevant code from the package](https://github.com/overtrue/vue-avatar-cropper/blob/39a8ed97e533df7e5b0149de0c1f6b780da0af56/src/vue-avatar-cropper.vue#L209-L217)

**Comment by cvalues** [comment]
okay, thanks alot!
