### ISSUE TITLE
A little confusing release info

### ISSUE THREAD

**Issue by LE-HU** [overtrue/vue-avatar-cropper#493]
Hello, just a heads up I've got to doublecheck release as I've just installed it and seen v.4 installed, while looking at github shows v.3. Maybe these can get in sync with what's shown on github/npmjs - thanks!
![v3](https://user-images.githubusercontent.com/19828138/133609670-90651de3-0b3e-494c-8c5b-4a71783c308f.png)
![v4](https://user-images.githubusercontent.com/19828138/133609820-7ce28ee5-e2ca-447d-b2d9-2bdc892380da.png)

Not sure also what version of Vue is being compatible here, vue-2, vue-3?

**Comment by ferretwithaberet** [comment]
We tried using tags once, that is why those releases are there(I cannot delete them, at least from the web application, maybe @overtrue can). Maybe in the future we will make the CI also generate the tag.
As for the supported Vue versions, `vue-avatar-cropper` only supports Vue 2 at the moment.

**Comment by overtrue** [comment]
@LE-HU Thanks for your feedback, this should be a historical issue, I have now removed them and only kept the version on npm.

**Comment by LE-HU** [comment]
thanks!
