### ISSUE TITLE
Cannot read property 'cancel' of undefined

### ISSUE THREAD

**Issue by MackieLee** [overtrue/vue-avatar-cropper#5]
wtf？

**Comment by hailwood** [comment]
@MackieLee 

This developer is providing this code free of charge as a service to you. They do not have to provide you with this service, nor do they have to provide you with support or bug fixes.

Perhaps try being respectful when submitting bug reports, make your description contain useful information: The version of the package, the browser, and actions that trigger the error etc.

Remember, you're not entitled to help here so appreciate the developers work.

**Comment by overtrue** [comment]
@hailwood Thanks.
