### ISSUE TITLE
Possible to use without upload functionality?

### ISSUE THREAD

**Issue by titusdecali** [overtrue/vue-avatar-cropper#507]
I'd like to get the file blob and then send it through an axios method that lives inside of Vuex, however I'm having trouble getting the file blob. I console logged each event, but don't see it there.

How can I access the cropped file to use it with my own uploader?

**Comment by ferretwithaberet** [comment]
There is the `upload-handler` prop to which you pass a function which takes a cropper.js instance. With the cropper.js instance you can then use `.getCroppedCanvas(options)` which results in a [`HTMLCanvasElement`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement), this object has a [`toBlob`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob) method. You can see this whole process being done in the source [here](https://github.com/overtrue/vue-avatar-cropper/blob/master/src/vue-avatar-cropper.vue#L292-L294).

**Comment by titusdecali** [comment]
For anyone else that wants a more concise answer:

`<avatar-cropper
     v-model="showAvatarModal"
     :upload-handler="uploadFile"
  />
`

`
methods: {
    uploadFile(cropperInstance) {
      const payload = cropperInstance.getCroppedCanvas().toDataURL()
      
      this.$store.dispatch('UPLOAD_AVATAR', payload)
    }
 }
`
