### ISSUE TITLE
toBlob() not supported on IE/Edge

### ISSUE THREAD

**Issue by jeffatprojectfinance** [overtrue/vue-avatar-cropper#56]
toBlob() is not supported on IE/Edge.  Any recommendations as to a fix/workaround?

**Comment by overtrue** [comment]
Please take a try: https://stackoverflow.com/questions/47475647/canvas-to-blob-on-edge

**Comment by overtrue** [comment]
https://github.com/fengyuanchen/cropperjs/issues/172
