### ISSUE TITLE
How can we turn off Capture?

### ISSUE THREAD

**Issue by ShehryarKh** [overtrue/vue-avatar-cropper#571]

**Comment by ferretwithaberet** [comment]
Do you mean the `capture` prop? It should be off by default.

**Comment by ShehryarKh** [comment]
@ferretwithaberet on mobile i have the option to take a photo, which i don't want.

<avatar-cropper
      @uploading="photoUploading = true"
      @uploaded="handleUploaded"
      @completed="handleCompleted"
      @error="handleError"
      :labels="{ submit: 'OK', cancel: 'Cancel' }"
      :output-mime="'image/png'"
      :trigger="getTrigger"
      :upload-handler="cropperHandler"
    />

**Comment by ferretwithaberet** [comment]
> on mobile i have the option to take a photo, which i don't want.

We cannot disable that due to how `<input type="file">` works. Even if you could, the user could just take a picture with their camera app and then select it normally.
