### ISSUE TITLE
Not working as expected within a form element

### ISSUE THREAD

**Issue by rpankaj** [overtrue/vue-avatar-cropper#58]
Cropping feature is working fine.
But my page (parent) is getting refreshed whenever I click on '****Submit**' or 'Cancel**' button.
What I noticed is page URL is changed from 
http://localhost:8080/myApp/#/admin/user/1
to 
http://localhost:8080/myApp/?note=#/admin/user/1

"?note=" came from where?

**Comment by rpankaj** [comment]
We can catch the submit event using '_uploaded_', '_completed_' etc...
**But is there any way to catch the cancel event in parent component?**

**Comment by rpankaj** [comment]
I found the reason and that is:
**if this component is used within a form element, parent page is being refreshed as mentioned above.**
Examples:
```
<form>
    <avatar-cropper
        @uploading="handleUploading"
        @uploaded="handleUploaded"
        @completed="handleCompleted"
        @error="handlerError"
        trigger="#pick-avatar"
        upload-url="https://demo.overtrue.me/upload.php" />
    </form>
```
Or
```
<v-form>
    <avatar-cropper
        @uploading="handleUploading"
        @uploaded="handleUploaded"
        @completed="handleCompleted"
        @error="handlerError"
        trigger="#pick-avatar"
        upload-url="https://demo.overtrue.me/upload.php" />
    </v-form>
```
So, this component should support it's usage within form element.

**Comment by overtrue** [comment]
@rpankaj Yes, I am working on this. plz wait a moment.

**Comment by overtrue** [comment]
@rpankaj Plz upgrade to 1.0.4 to fix this.

**Comment by overtrue** [comment]
And there has a demo: 


[![Edit test-project](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/github/overtrue/vue-avatar-cropper-demo/tree/master/)

**Comment by rpankaj** [comment]
Thanks a lot @overtrue 

What is the maximum size of image acceptable for this component?
Please mention the limitation regarding acceptable size and format etc...
