### ISSUE TITLE
node_modules vue-avatar-cropper folder contains no src or dist files

### ISSUE THREAD

**Issue by VladZen** [overtrue/vue-avatar-cropper#594]
I was trying to install the latest version of the package (6.0.0), but in the `node_modules` folders I see this

![](http://joxi.ru/Q2KVNkqILjGpZm.jpg)

**Comment by VladZen** [comment]
It still has no effect BTW

**Comment by overtrue** [comment]
@VladZen Plz take a try with 6.0.10. Thanks.
