### ISSUE TITLE
Upload failed when crop area is not small

### ISSUE THREAD

**Issue by rpankaj** [overtrue/vue-avatar-cropper#60]
I'm not able to understand the reason behind upload failure.
**Is there any restriction on image size or dimension?** If it is, what is the maximum size of image acceptable for this component?
Please mention the limitation regarding acceptable size and format etc...

![Video-Fri-Apr-26-2019-17-19-17](https://user-images.githubusercontent.com/6755944/56805741-9697ac80-6847-11e9-8929-0d1a4897f2a5.gif)

The image I'm using is:
![treetimelapse2](https://user-images.githubusercontent.com/6755944/56805964-305f5980-6848-11e9-812d-9989f7a7cd5e.jpg)

**Comment by rpankaj** [comment]
FYI @overtrue.
Can you please take a look on this once

**Comment by overtrue** [comment]
plz paste the error from server.

**Comment by rpankaj** [comment]
When I am trying to upload a 7kb file, cropper makes it 392kb and trying to upload.
This is because "**output-options**" has `{width: 512, height: 512}` as default value.
I can use `:output-options="{width: 256, height: 256}"` for now, but I don't think this is feasible solution.

Is there a way that the dimension of the image remains same before and after cropping the image?

**Comment by overtrue** [comment]
I have removed the default output options
