### ISSUE TITLE
this.$emit is not a function

### ISSUE THREAD

**Issue by razukc** [overtrue/vue-avatar-cropper#7]
![console](https://user-images.githubusercontent.com/4814921/32778778-4e79360a-c963-11e7-839f-54f3356635ad.png)
![script](https://user-images.githubusercontent.com/4814921/32778784-5362d09a-c963-11e7-9fc2-d7ce7e14d04b.png)

**Comment by overtrue** [comment]
vue 正确引入了？

**Comment by razukc** [comment]
Well, the upload works fine; however, does not reach 'uploaded' method; here is my code:
` <user-image 
              trigger="#set-avatar" 
              :labels="{submit: 'Ok', cancel: 'Cancel'}" 
              @uploaded="handleUploaded"
              @uploading="handleUploading"
              upload-form-name="profile_picture"
              upload-url="/control/public/api/postProfilePicture">
</user-image>`

`methods: {
      handleUploading(form, xhr) {
        form.append('remember_token', this.remember_token)
        var blob = form.get('profile_picture')
        var filename = blob.type.replace('/','.')
        form.set('profile_picture', blob, filename)
      },
      handleUploaded(response, form, xhr){
         console.log(response)
      },
    }`

**Comment by razukc** [comment]
Can you provide a basic example using 'upload-handler'?

**Comment by overtrue** [comment]
https://codesandbox.io/s/github/overtrue/vue-avatar-cropper-demo
