### ISSUE TITLE
JPG to PNG results into corrupt

### ISSUE THREAD

**Issue by bchuuk** [overtrue/vue-avatar-cropper#78]
Hi
When we upload JPG image (either for resizing or for cropping) we store the resulted image into .PNG file format.
We can open and access the resulted PNG image without any problem.
But internally we found resulted PNG images are having corrupt PNG Headers

'file' => 
    array (size=5)
      'name' => string '132.jpg' (length=7)
      'type' => string 'image/png' (length=9)
      'tmp_name' => string '/tmp/phpmSDIUl' (length=14)
      'error' => int 0
      'size' => int 105091

**Comment by waLplanet** [comment]
> Hi
> When we upload JPG image (either for resizing or for cropping) we store the resulted image into .PNG file format.
> We can open and access the resulted PNG image without any problem.
> But internally we found resulted PNG images are having corrupt PNG Headers
> 
> 'file' =>
> array (size=5)
> 'name' => string '132.jpg' (length=7)
> 'type' => string 'image/png' (length=9)
> 'tmp_name' => string '/tmp/phpmSDIUl' (length=14)
> 'error' => int 0
> 'size' => int 105091

hi bchuuk,
the plugin works perfectly..
can you reproduce that weird behaviour in codesandbox or similar?
