### ISSUE TITLE
Zoom in / Zoom out buttons?

### ISSUE THREAD

**Issue by mityaua** [overtrue/vue-avatar-cropper#783]
Is it possible to add zoom-in / and zoom-out buttons inside a modal window? (somewhere near cancel and upload buttons).

![image](https://github.com/overtrue/vue-avatar-cropper/assets/20481332/df3cf8ad-383f-45da-b3ef-dc659692ba31)

**Comment by overtrue** [comment]
```html
:cropper-options="{ zoomable: true }"
```

**Comment by overtrue** [comment]
Sorry, I don't want to add extra buttons to this component, I  would like to keep it simple, you can fork this repo and make some changes.

**Comment by mityaua** [comment]
> Sorry, I don't want to add extra buttons to this component, I  would like to keep it simple, you can fork this repo and make some changes. 

You can add default (or named) slot, without any logic. It's good opportunity to extend preview by additional controls (zoom, rotate, or what have you). And component will be simple too.

**Comment by overtrue** [comment]
> > Sorry, I don't want to add extra buttons to this component, I  would like to keep it simple, you can fork this repo and make some changes. 
> 
> You can add default (or named) slot, without any logic. It's good opportunity to extend preview by additional controls (zoom, rotate, or what have you). And component will be simple too.

OK，I'll add it.

**Comment by overtrue** [comment]
@mityaua 6.1.0 has been released. Thanks.
