### ISSUE TITLE
当trigger指向的是另一个组件时，组件运行存在异常，error事件也不触发，上传文件的对话框也不弹出

### ISSUE THREAD

**Issue by zazaluMonster** [overtrue/vue-avatar-cropper#96]
我在进行一个简单的vue单组件开发一个头像上传页面

使用Usage里提供的demo代码，可以正常使用。

异常情况描述：
上传按钮使用的不是原生的html标签<button>，而是另一个人写的Button组件，然后导致了一些问题。

我的代码：
```vue
<template>
<!-- 注意是另一个Button组件，不是原生的<button> -->
<Button id="pick-avatar">上传头像</Button>  
<avatar-cropper
            @uploaded="handleUploaded"
            @error="handleError"
            trigger="#pick-avatar"
            upload-url="/files/upload"
          />
</template>

<script>
//因为js代码没啥东西，先省略
</script>
```

最后的效果就是点击button没有反应

我自己推测应该是`document.querySelector`的机制导致没有找到组件加载后的id为pick-avatar的button元素。

所以目前暴露的API好像不够支持这种情况，希望可以提供下在父组件内手动触发trigger对应的内部函数的API。

我是vue新手，有些措辞可能不准确！

**Comment by ferretwithaberet** [comment]
I translated this text using Google Translate and it seems that this is related to #436, when I will implement the fix for #436 this will also be closed as you will be able to use the @click emitted by the custom button component to trigger the avatar cropper.
